### ISSUE TITLE
Limit TimedSignature to a Single Use Per Instance

### ISSUE THREAD

**Issue by peaceandwhisky** [mycel-labs/astraeus#35]
Currently, a user-created TimedSignature can be reused across different functions. Since the utilized TimedSignature is outputted in the node’s event logs, anyone other than the creator can easily reference and reuse it.

This poses a security risk, allowing others to impersonate the original creator and use the TimedSignature.

To address this, we plan to introduce a nonce within the TimedSignature. The nonces will be managed during the TimedSignature verification process, ensuring that only the TimedSignature with the latest nonce can be used. This will prevent unauthorized reuse of outdated signatures.

This version clearly explains the current issue, the risk, and the intended solution.

**Comment by taryune** [comment]
add calldata verification
