### ISSUE TITLE
Rename Param: Curve -> SignatureAlgorithm

### ISSUE THREAD

**Issue by taryune** [mycel-labs/astraeus#49]
target:
https://github.com/mycel-labs/astraeus/blob/f5fee8c6ae89d91527f49d61d20d1b886efd1142/src/solidity/interfaces/ITransferableAccountStore.sol#L17-L21

https://github.com/mycel-labs/astraeus/blob/f5fee8c6ae89d91527f49d61d20d1b886efd1142/src/proto/api/v1/transferable_account.proto#L19-L23

reference:
https://github.com/mycel-labs/astraeus-ic/blob/cb36411f5f25ee2038d0b8d855d16431e7c45c01/src/astraeus_ic_backend/src/threshold_signer.rs#L43-L51

**Comment by foxytanuki** [comment]
```solidity
enum SignatureAlgorithm { 
     CURVE_UNKNOWN, 
     ECDSA, 
     EDDSA 
 } 
 ```
 
 ```proto
 enum SignatureAlgorithm { 
   SignatureAlgorithm_UNSPECIFIED = 0; 
   SignatureAlgorithm_ECDSA = 1; 
   SignatureAlgorithm_EDDSA = 2; 
 } 
 ```
